version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    environment:
      - DEBUG=False
    restart: unless-stopped
    networks:
      - osint-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - API_URL=http://backend:8000
    networks:
      - osint-network

networks:
  osint-network:
    driver: bridge 