version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./exports:/app/exports
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - osint-network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - osint-network

networks:
  osint-network:
    driver: bridge 